name: money_overview
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  http: ^0.13.4
  flutter_svg: ^1.0.3
  hive: ^2.0.5
  provider: ^6.0.2
  currency_picker: ^2.0.7
  quiver: ^3.0.1+1
  font_awesome_flutter: ^9.2.0
  intl: ^0.17.0
  simple_gradient_text: ^1.2.2
  uuid: ^3.0.5
  hive_flutter: ^1.1.0
  path_provider: ^2.0.8
  currency_pickers: ^1.0.6
  flutter_launcher_icons: ^0.9.2
  syncfusion_flutter_charts: ^19.4.53
  flutter_cupertino_date_picker:
    git: https://github.com/winteragency/flutter-cupertino-date-picker.git

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  hive_generator: ^1.1.2
  build_runner: ^2.1.7


flutter_icons:
  #image_path: "assets/images/logo.png"
  image_path_android: "assets/images/logo.png"
  image_path_ios: "assets/images/logo.png"
  android: true
  ios: true
  remove_alpha_ios: true
  adaptive_icon_background: "assets/images/background.png" # only available for Android 8.0 devices and above
  adaptive_icon_foreground: "assets/images/foreground.png" # only available for Android 8.0 devices and above

flutter:
  uses-material-design: true
  fonts:
    - family: Izmir
      fonts:
        - asset: assets/fonts/Izmir/Izmir-Thin.otf
          weight: 100
          style: normal
        - asset: assets/fonts/Izmir/Izmir-ThinItalic.otf
          weight: 100
          style: italic
        - asset: assets/fonts/Izmir/Izmir-Extralight.otf
          weight: 200
          style: normal
        - asset: assets/fonts/Izmir/Izmir-ExtralightItalic.otf
          weight: 200
          style: italic
        - asset: assets/fonts/Izmir/Izmir-Light.otf
          weight: 300
          style: normal
        - asset: assets/fonts/Izmir/Izmir-LightItalic.otf
          weight: 300
          style: italic
        - asset: assets/fonts/Izmir/Izmir-Regular.otf
          weight: 400
          style: normal
        - asset: assets/fonts/Izmir/Izmir-RegularItalic.otf
          weight: 400
          style: italic
        - asset: assets/fonts/Izmir/Izmir-Medium.otf
          weight: 500
          style: normal
        - asset: assets/fonts/Izmir/Izmir-MediumItalic.otf
          weight: 500
          style: italic
        - asset: assets/fonts/Izmir/Izmir-Semibold.otf
          weight: 600
          style: normal
        - asset: assets/fonts/Izmir/Izmir-SemiboldItalic.otf
          weight: 600
          style: italic
        - asset: assets/fonts/Izmir/Izmir-Bold.otf
          weight: 700
          style: normal
        - asset: assets/fonts/Izmir/Izmir-BoldItalic.otf
          weight: 700
          style: italic
        - asset: assets/fonts/Izmir/Izmir-Extrabold.otf
          weight: 800
          style: normal
        - asset: assets/fonts/Izmir/Izmir-ExtraboldItalic.otf
          weight: 800
          style: italic
        - asset: assets/fonts/Izmir/Izmir-Black.otf
          weight: 900
          style: normal
        - asset: assets/fonts/Izmir/Izmir-BlackItalic.otf
          weight: 900
          style: italic